name: Deploy a LAMP stack on a remote host using Kubernetes

on:
  #push:
  workflow_dispatch:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Remote Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to project directory on local machine
          cd /path/to/your/app

          # login to dhi.io
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login dhi.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          # Pull latest changes from git
          git pull origin main

          # Setup
          sh setup.sh

          # Deploy docker compose
          docker compose --build --remove-orphans

    - name: Verify Kubernetes Cluster Connection
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy LAMP stack cluster
      run: |
        kubectl apply -f k8s_lampstack_deploy.yaml

    - name: Check Deployment Status
      run: |
        kubectl rollout status deployment/mysql
        kubectl rollout status deployment/apache-php
        kubectl get svc
