name: Build and Deploy LAMP stack to K8s

on:
  #push:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}


    - name: Deploy to Remote Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to project directory on local machine
          cd /path/to/your/app

          # login to dhi.io
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login dhi.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          # Pull latest changes from git
          git pull origin main

          # Setup
          sh setup.sh

          # Restart docker compose
          docker compose up -d --build --remove-orphans

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3

    - name: Authenticate to K8s Cluster
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy to Kubernetes cluster
      uses: azure/k8s-deploy@v5
      with:
        manifests: |
          kubernetes/mysql-deployment.yaml
        images: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
